import { Occupant, LedgerBlock } from "./types";

// Initial tokenized occupant roster simulating Floor 7 occupants (Pilot team of ConEdison, 4 Irving Plaza)
// They are "Tokenized-at-Rest" (names replaced with GUIDs, shown as masked strings initially).
export const INITIAL_OCCUPANTS: Occupant[] = [
  {
    id: "usr_a7f8c9d1",
    badgeId: "NW449210",
    nameEncrypted: "J••• D••", // Masked initially (Vault tokenization simulation)
    role: "Warden",
    status: "SAFE",
    quadrant: "NW",
    staircase: "Stair A",
    musterZone: "Zone A",
    lastSeen: "10:02 AM",
    fallDetected: false,
    drillParticipant: true,
    nextOfKinRegistered: true,
    nextOfKinNotified: true,
  },
  {
    id: "usr_f9e3c2b8",
    badgeId: "FA018239",
    nameEncrypted: "B•• J••••",
    role: "Contractor",
    status: "MISSING",
    quadrant: "Center",
    lastSeen: "09:55 AM",
    fallDetected: false,
    drillParticipant: true,
  },
  {
    id: "usr_b3c7d6e5",
    badgeId: "HR551109",
    nameEncrypted: "A•••• S••••",
    role: "Occupant",
    status: "NEED_HELP",
    quadrant: "NE",
    lastSeen: "10:04 AM",
    alertNote: "Fume inhalation near breakroom, assisting with mobility.",
    fallDetected: false,
    mobilityImpaired: true,
    isAtARA: true,
    nextOfKinRegistered: true,
    drillParticipant: true,
  },
  {
    id: "usr_d4e3f2a1",
    badgeId: "LS990011",
    nameEncrypted: "M••••• L••",
    role: "FSD",
    status: "SAFE",
    quadrant: "Center",
    staircase: "Stair A",
    musterZone: "Zone A",
    lastSeen: "10:00 AM",
    fallDetected: false,
    drillParticipant: true,
  },
  {
    id: "usr_c1b2a3d4",
    badgeId: "NW112233",
    nameEncrypted: "C••••• J••••••",
    role: "Occupant",
    status: "MISSING",
    quadrant: "NW",
    lastSeen: "09:58 AM",
    fallDetected: false,
    drillParticipant: true,
  },
  {
    id: "usr_e5f6a7b8",
    badgeId: "FI338822",
    nameEncrypted: "D•••• M•••••",
    role: "Occupant",
    status: "CRITICAL",
    quadrant: "SE",
    lastSeen: "10:05 AM",
    alertNote: "On-Device fall sensor triggered.",
    fallDetected: true,
    wearable: true,
    nextOfKinRegistered: true,
    drillParticipant: true,
  },
  {
    id: "usr_s7t8u9v0",
    badgeId: "SE556677",
    nameEncrypted: "L••• T•••••",
    role: "Occupant",
    status: "NEED_HELP",
    quadrant: "SE",
    lastSeen: "10:04 AM",
    alertNote:
      "Crutches — staged at Area of Rescue Assistance, awaiting evac-chair.",
    fallDetected: false,
    mobilityImpaired: true,
    isAtARA: true,
    nextOfKinRegistered: true,
    drillParticipant: true,
  },
  {
    // Mobility-impaired, still en-route — demonstrates the IN TRANSIT path
    // on the ARA Evac-Chair Priority Board (isAtARA: false floats to top).
    id: "usr_p2q3r4s5",
    badgeId: "SW773344",
    nameEncrypted: "R•••••• P•••",
    role: "Occupant",
    status: "NEED_HELP",
    quadrant: "SW",
    lastSeen: "10:06 AM",
    alertNote: "En route to Stair A landing — evac-chair not yet reached.",
    fallDetected: false,
    mobilityImpaired: true,
    isAtARA: false,
    nextOfKinRegistered: true,
    drillParticipant: true,
  },
  {
    // 4th mobility-impaired occupant — staged at ARA on NE stairwell landing
    id: "usr_m4n5o6p7",
    badgeId: "NE884422",
    nameEncrypted: "V•• O•••••",
    role: "Occupant",
    status: "NEED_HELP",
    quadrant: "NE",
    lastSeen: "10:07 AM",
    alertNote: "Staged at ARA on NE stairwell landing — awaiting evac-chair.",
    fallDetected: false,
    mobilityImpaired: true,
    isAtARA: true,
    nextOfKinRegistered: true,
    drillParticipant: true,
  },
  {
    // EAP Searcher — NE quadrant sweep team
    id: "usr_sr1ne334",
    badgeId: "SR334455",
    nameEncrypted: "T•••• M•••••",
    role: "Searcher",
    status: "SAFE",
    quadrant: "NE",
    staircase: "Stair A",
    musterZone: "Zone A",
    lastSeen: "10:08 AM",
    fallDetected: false,
    drillParticipant: true,
    nextOfKinRegistered: true,
  },
  {
    // EAP Searcher — SW quadrant sweep team
    id: "usr_sr2sw667",
    badgeId: "SR667788",
    nameEncrypted: "H•••• C••••",
    role: "Searcher",
    status: "SAFE",
    quadrant: "SW",
    staircase: "Stair A",
    musterZone: "Zone A",
    lastSeen: "10:08 AM",
    fallDetected: false,
    drillParticipant: true,
    nextOfKinRegistered: true,
  },
  {
    // EAP Deputy — backs up the Floor Warden, runs corridor accountability
    id: "usr_dpct990",
    badgeId: "DP990011",
    nameEncrypted: "K••• B•••••",
    role: "Deputy",
    status: "SAFE",
    quadrant: "Center",
    staircase: "Stair A",
    musterZone: "Zone A",
    lastSeen: "10:02 AM",
    fallDetected: false,
    drillParticipant: true,
    nextOfKinRegistered: true,
  },
  {
    id: "usr_va1b2c3d4",
    badgeId: "VIS00201",
    nameEncrypted: "T•• C••••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "NE",
    lastSeen: "09:45 AM",
    alertNote: "Lobby sign-in. Badge VIS00201.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_ve5f6a7b8",
    badgeId: "VIS00202",
    nameEncrypted: "P•••• R•••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "SW",
    lastSeen: "09:47 AM",
    alertNote: "Lobby sign-in. Badge VIS00202.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_vc3d4e5f6",
    badgeId: "VIS00203",
    nameEncrypted: "M•• H••••••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "Center",
    lastSeen: "09:49 AM",
    alertNote: "Lobby sign-in. Badge VIS00203.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_v6a7b8c9d",
    badgeId: "VIS00204",
    nameEncrypted: "J•• A•••••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "NW",
    lastSeen: "09:51 AM",
    alertNote: "Lobby sign-in. Badge VIS00204.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_v3e4f5a6b",
    badgeId: "VIS00205",
    nameEncrypted: "K••• W•••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "SE",
    lastSeen: "09:53 AM",
    alertNote: "Lobby sign-in. Badge VIS00205.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_v7c8d9e0f",
    badgeId: "VIS00206",
    nameEncrypted: "R•• B••••••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "NE",
    lastSeen: "09:54 AM",
    alertNote: "Lobby sign-in. Badge VIS00206.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_v4b5c6d7e",
    badgeId: "VIS00207",
    nameEncrypted: "A•••• N•••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "SW",
    lastSeen: "09:55 AM",
    alertNote: "Lobby sign-in. Badge VIS00207.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_v8f9a0b1c",
    badgeId: "VIS00208",
    nameEncrypted: "G•• F•••••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "Center",
    lastSeen: "09:56 AM",
    alertNote: "Lobby sign-in. Badge VIS00208.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_v1d2e3f4a",
    badgeId: "VIS00209",
    nameEncrypted: "L•••• D••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "SE",
    lastSeen: "09:57 AM",
    alertNote: "Lobby sign-in. Badge VIS00209.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_v5b6c7d8e",
    badgeId: "VIS00210",
    nameEncrypted: "C••• M•••••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "NW",
    lastSeen: "09:58 AM",
    alertNote: "Lobby sign-in. Badge VIS00210.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
  {
    id: "usr_k9l0m1n2",
    badgeId: "VIS00101",
    nameEncrypted: "S••••• W••••",
    role: "Visitor",
    status: "MISSING",
    quadrant: "NW",
    lastSeen: "09:52 AM",
    alertNote:
      "Lobby sign-in 10 min before alarm. Lobby-issued badge VIS00101.",
    fallDetected: false,
    isVisitor: true,
    drillParticipant: false,
  },
];

// Seed ledger blocks (Hash-Chained Ledger)
export const SEED_LEDGER: LedgerBlock[] = [
  {
    index: 0,
    timestamp: "2026-05-28T10:00:00Z",
    event:
      "Alarm triggered on Floor 7 (Pilot Phase). Fire Command System online.",
    prevHash:
      "0000000000000000000000000000000000000000000000000000000000000000",
    hash: "6e2e50550c6204b77f27af851532f83138b320876189daabc7cd23ebf90b0d62",
  },
  {
    index: 1,
    timestamp: "2026-05-28T10:02:15Z",
    event:
      "Occupant token usr_a7f8c9d1 (Warden) scanned badge at Stair A NFC gate: SAFE.",
    prevHash:
      "6e2e50550c6204b77f27af851532f83138b320876189daabc7cd23ebf90b0d62",
    hash: "f4007bbf519ff7f99ee70bfbdfce09f6eeb62f3a469446d376ca743ec9ef906a",
  },
  {
    index: 2,
    timestamp: "2026-05-28T10:04:10Z",
    event:
      "Occupant token usr_b3c7d6e5 updated status: NEED_HELP. Fume alert logged.",
    prevHash:
      "f4007bbf519ff7f99ee70bfbdfce09f6eeb62f3a469446d376ca743ec9ef906a",
    hash: "fbbf56edbcf52ae2e2764bbf63be1da4efba293818de77678ca902bcfaaeef90",
  },
];

// ConEdison Floor 7 EAP — designated assembly areas
export const MUSTER_ZONES = [
  {
    id: "Zone A",
    label: "Zone A - Stuyvesant Square Park",
    desc: "PRIMARY Assembly Area (btwn 17th & 15th St) [RECOMMENDED]",
  },
  {
    id: "Zone B",
    label: "Zone B - Union Square Park",
    desc: "SECONDARY Assembly Area (along E 14th St)",
  },
];

// ConEdison Floor 7 EAP — 12 emergency event types the FSD may declare
export const EAP_EMERGENCY_TYPES = [
  { id: "Fire/Smoke", label: "Fire / Smoke", icon: "🔥" },
  { id: "Explosion", label: "Explosion", icon: "💥" },
  { id: "Medical", label: "Medical", icon: "🩺" },
  { id: "Biological", label: "Biological", icon: "🧪" },
  { id: "Chemical Release", label: "Chemical Release", icon: "☣️" },
  { id: "Radiological", label: "Radiological", icon: "☢️" },
  { id: "Nuclear", label: "Nuclear", icon: "⚛️" },
  { id: "Natural Disaster", label: "Natural Disaster", icon: "🌪️" },
  { id: "Active Shooter", label: "Active Shooter", icon: "🚨" },
  { id: "Bomb Threat", label: "Bomb Threat", icon: "💣" },
  { id: "Suspicious Package", label: "Suspicious Package", icon: "📦" },
  { id: "Other", label: "Other", icon: "❓" },
] as const;

// Three LSD/FSD decision branches per Floor 7 EAP
export const EAP_DECISIONS = [
  {
    id: "EVACUATE",
    label: "Evacuate",
    desc: "Full or partial floor evacuation via designated stairs",
  },
  {
    id: "SHELTER_IN_PLACE",
    label: "Shelter in Place",
    desc: "Occupants remain in current secure area",
  },
  {
    id: "IN_BUILDING_RELOCATION",
    label: "In-Building Relocation",
    desc: "Move occupants to another floor / safe zone in building",
  },
] as const;

// Floor 7 elevator recall — only these two cars are authorized
// (all others recall to lobby; no occupant elevator use during fire/explosion)
export const ELEVATOR_RECALL = [
  {
    bank: "A-Bank",
    carNumber: 14,
    status: "AUTHORIZED" as const,
    note: "Authorized for FSD / FDNY use",
  },
  {
    bank: "G-Bank",
    carNumber: 1,
    status: "AUTHORIZED" as const,
    note: "Authorized for FSD / FDNY use",
  },
];

// Floor 7 sweep quadrants — warden sweep coverage target ≥ 98%
export const SWEEP_QUADRANTS = ["NW", "NE", "SW", "SE", "Center"] as const;

// FDNY / NYC LL26 record retention requirement
export const RECORD_RETENTION_YEARS = 10;
